# Importing Libraries

In [46]:
import numpy as np
#from itertools import tee

In [47]:
def softmax(a):
    e_pa=np.exp(a)
    ans=e_pa/np.sum(e_pa, axis=1, keepdims=True)
    return ans

In [61]:
class NewNeuralNetwork:
    
    def __init__(self, input_size, layers, no_of_layers, output_size):
        
        np.random.seed(0)
        
        total_layers=[input_size]
        total_layers.extend(layers)
        total_layers.append(output_size)
        layers=total_layers
        no_of_layers+=2
        
        model={}
        
        # Implementation of MLP
        for i in range (no_of_layers-1):
            
            model[i] = [np.random.randn(layers[i], layers[i+1]), np.zeros((1, layers[i+1]))]
   
            #model[np.random.randn(layers[i], layers[i+1])] = np.zeros((1, layers[i]))
        
        self.model=model
        
        
    def forward(self, x):
            
        count=1
        model_size=len(self.model)
        print(model_size)    
        temp_model=self.model
        #print(temp_model)
        for key in self.model:
            #print('hello')   
            if count==1:
                    
                z=np.dot(x, temp_model[key][0]) + temp_model[key][1]
                a=np.tanh(z)
                #print(a)
                
            elif count>1 and count != model_size:
                  
                z=np.dot(a, temp_model[key][0]) + temp_model[key][1]
                a=np.tanh(z)
                #print(a)
                    
            else:
                z=np.dot(a, temp_model[key][0]) + temp_model[key][1]
                a = softmax(z)
                #print(a)
                return a                 
            
            count+=1
                    
                    
        

In [68]:
n=NewNeuralNetwork(3,[4,3],2,3)
ans=n.forward(7)
print('output: \n', ans)

3
hello
hello
hello
output: 
 [[0.38133641 0.04068    0.57798359]
 [0.7382219  0.04793076 0.21384734]
 [0.2205953  0.08064455 0.69876015]]


In [8]:
# Model Parameters
input_size=int(input()) # No of Features = No. of node in I/P Layer
no_of_layer=int(input())
layers=[] # Number of Neurons in each Layer
print('enter the number of Neurons in each layer: ')
for i in range (no_of_layer):
    temp=int(input())
    layers.append(temp)
output_size=int(input())
n=NewNeuralNetwork(2,[4,3],2,2)
ans=n.forward(5)
print('output: \n', ans)

1
1
enter the number of Neurons in each layer: 
1
1


AttributeError: 'NewNeuralNetwork' object has no attribute 'forward'

In [40]:
model={}
model[0]=[4,2]
for key in model:
    print(model[key][1])

2


In [47]:
"""class NeuralNetwork:
    
    def __init__(self, input_size, layers,no_of_layer, output_size):
        np.random.seed(0)
        
        model={}
        count=0
        model[count]=np.random.randn(input_size, layers[0])
        model[count+1]=np.zeros((1, layers[0]))
        count+=2
        for i in range (1,no_of_layer):
            model[count]=np.random.randn(layers[i-1], layers[i])
            model[count+1]=np.zeros((1, layers[i]))
            count+=2

            #model['W2']=np.random.randn(layers[0], layers[1])
            #model['b2']=np.zeros((1, layers[1]))


            #model['W3']=np.random.randn(layers[1], output_size)
            #model['b3']=np.zeros((1, output_size))
        
        model[count]=np.random.randn(layers[no_of_layer-1],output_size)
        model[count+1]=np.zeros((1,output_size))
        self.model=model
        
        
    def forward(self, x):

        #W1,W2,W3=self.model['W1'],self.model['W2'],self.model['W3']
        #b1,b2,b3=self.model['b1'],self.model['b2'],self.model['b3']
        #print(self.model)
        count=0
        z=np.dot(x,self.model[count])+self.model[count+1]
        a=np.tanh(z)
        count+=2
        #print(a)
        z=np.dot(a,self.model[count])+self.model[count+1]
        a=np.tanh(z)
        #print(a)
        count+=2
        #for i in range (no_of_layer-1):
         #   print(i)
         #   z=np.dot(a,self.model[count])+self.model[count+1]
          #  a=np.tanh(z)
          #  count+=2
            
            
        #z1=np.dot(x,W1)+b1
        #a1=np.tanh(z1)

        #z2=np.dot(a1, W2)+b2
        #a2=np.tanh(z2)

        z=np.dot(a, self.model[count])+self.model[count+1]
        y_=softmax(z)
        
        return y_"""

"class NeuralNetwork:\n    \n    def __init__(self, input_size, layers,no_of_layer, output_size):\n        np.random.seed(0)\n        \n        model={}\n        count=0\n        model[count]=np.random.randn(input_size, layers[0])\n        model[count+1]=np.zeros((1, layers[0]))\n        count+=2\n        for i in range (1,no_of_layer):\n            model[count]=np.random.randn(layers[i-1], layers[i])\n            model[count+1]=np.zeros((1, layers[i]))\n            count+=2\n\n            #model['W2']=np.random.randn(layers[0], layers[1])\n            #model['b2']=np.zeros((1, layers[1]))\n\n\n            #model['W3']=np.random.randn(layers[1], output_size)\n            #model['b3']=np.zeros((1, output_size))\n        \n        model[count]=np.random.randn(layers[no_of_layer-1],output_size)\n        model[count+1]=np.zeros((1,output_size))\n        self.model=model\n        \n        \n    def forward(self, x):\n\n        #W1,W2,W3=self.model['W1'],self.model['W2'],self.model['W3']\n 

In [48]:
# initializing list
"""test_list = [0, 1, 2, 3, 4, 5]

# printing original list
print (test_list)

# using list comprehension
# to perform pair iteration in list
res = [((i), (i + 1) % len(test_list)) for i in range(len(test_list))]

# printing result
for i in res:
    print(i[0,1])
"""

'test_list = [0, 1, 2, 3, 4, 5]\n\n# printing original list\nprint (test_list)\n\n# using list comprehension\n# to perform pair iteration in list\nres = [((i), (i + 1) % len(test_list)) for i in range(len(test_list))]\n\n# printing result\nfor i in res:\n    print(i[0,1])\n'

# Softmax Function